---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/enhancements/pull/1870"
  name: noderesourcetopologies.topology.node.k8s.io
spec:
  group: topology.node.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            topologyPolicies:
              type: array
              items:
                type: string
            zones:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  parent:
                    type: string
                  resources:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        capacity:
                          x-kubernetes-int-or-string: true
                        allocatable:
                          x-kubernetes-int-or-string: true
                  costs:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: integer
                  attributes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
  scope: Namespaced
  names:
    plural: noderesourcetopologies
    singular: noderesourcetopology
    kind: NodeResourceTopology
    shortNames:
      - node-res-topo
